285 rfm model
CodeForPhilly/paws-data-pipeline pull request #420
Opened 2021-08-10 22:44 UTC by bdeck8317

Moved rfm functions to 
`src/server/rfm/`

2021-08-11 01:57 UTC, c-simpson requested changes
What do we do with the giant html files?
Can you add some comments that explain how to run your code?  Where to start?
What do you do with the scores when you are finished?
(See other comments below)

2021-08-11 01:57 UTC, c-simpson commented on src/server/rfm/rfm_funcs/amount_bins.py
> +    # human_amount_bins = np.insert(bins, 5, upper_bin)
Any reason not to remove the commented-out code?

2021-08-11 01:57 UTC, c-simpson commented on src/server/rfm/rfm_funcs/create_bins.py
> +    donations_df = pd.read_csv('csv')
Aren't we getting data from tables (via `pull_donations_for_rfm()`), not from files?

2021-08-11 01:57 UTC, c-simpson commented on src/server/rfm/rfm_funcs/create_bins.py
> +    donations_df['Close_Date'] =pd.to_datetime(donations_2021['Close_Date']).dt.date
Could we use a variable name more general than `donations_2021`?

2021-08-11 01:57 UTC, c-simpson commented on src/server/rfm/rfm_funcs/create_bins.py
> +            final_frequency_bins = human_frequency_bins
Are these supposed to be the same variable? If not, maybe change one to be less similar.

2021-08-11 01:57 UTC, c-simpson commented on src/server/rfm/rfm_funcs/create_scores.py
> +    df = pd.read_csv(path_to_csv)
CSV file?

2021-08-11 01:57 UTC, c-simpson commented on src/server/rfm/rfm_funcs/create_scores.py
> +    donations_2021 = df
**donations_past_year** maybe?

2021-08-11 01:57 UTC, c-simpson commented on src/server/rfm/rfm_funcs/create_scores.py
> +        # calculate date difference between input date and
input date and.. ?

2021-08-11 01:57 UTC, c-simpson commented on src/server/rfm/rfm_funcs/create_scores.py
> +    grouped_2021 = donations_2021.groupby('_id').agg({'days_since': ['min']}).reset_index()
Same concern about 2021

2021-08-11 01:57 UTC, c-simpson commented on src/server/rfm/rfm_funcs/rfm_functions.py
> +    from datetime import datetime, date
Can you add a docstring - what does the diff represent  - days?

2021-08-11 14:14 UTC, bdeck8317 commented
I will make all the above changes and create a new pull request!

2021-08-16 14:22 UTC, bdeck8317 commented
All requested changes have been made. Removed the html doc and created a readme.md for process of running the functions.

2021-08-16 14:22 UTC, closed without merging